version: "3.8"

services:
  backend:
    build: ./backend
    container_name: prompt_backend
    ports:
      - "7979:7979"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: prompt_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
