version: "3.8"

services:
  backend:
    build: ./backend
    container_name: prompt_backend
    expose:
      - "7979"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    environment:
      - CORS_ORIGIN=${BACKEND_CORS_ORIGIN}

  frontend:
    build: ./frontend
    container_name: prompt_frontend
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
